### ISSUE TITLE
Repository 'go-dotaccess' not found while installing

### ISSUE THREAD

**Issue by yaronius** [go-bongo/bongo#19]
When I try to import the library, I get error about missing dependency which is not present on GitHub:
> go get github.com/maxwellhealth/bongo
> cd .; git clone https://github.com/maxwellhealth/go-dotaccess /Users/user/go/src/github.com/maxwellhealth/go-dotaccess
> Cloning into '/Users/user/go/src/github.com/maxwellhealth/go-dotaccess'...
> remote: Repository not found.
> fatal: repository 'https://github.com/maxwellhealth/go-dotaccess/' not found
> package github.com/maxwellhealth/go-dotaccess: exit status 128

**Comment by securingsincity** [comment]
@yaronius this should be resolved now. We're in the processing of moving around some older repos and that got deleted in the process.

**Comment by yaronius** [comment]
Thank you, it does work now!
