### ISSUE TITLE
Not sure what "Cascading" does?

### ISSUE THREAD

**Issue by lucaswxp** [go-bongo/bongo#20]
hey guys.

Sorry for the noob question, but I couldn't understand what "cascade" actually means in this sentence:

```
you can cascade a player's first name and last name to his or her team.Players array on save, and remove that element in the array if you delete the player.
```

Supposing I have the following "team", in what could cascade help-me?
```
[
	{
		"team": "Team A",
		"players": [
			{
				"firstname": "Player",
				"lastname": "1"
			},
			{
				"firstname": "Player",
				"lastname": "2"
			},
			{
				"firstname": "Player",
				"lastname": "3"
			}
		]
	}
]
```

**Comment by securingsincity** [comment]
@lucaswxp the idea is that the Team's players could be managed through the team. In the example, the behavior is similar to how an ORM would manage a one-to-many relationship. In bongo one document contains all of those elements.

**Comment by lucaswxp** [comment]
@securingsincity I think I got it. Thanks!
