### ISSUE TITLE
How to Modify Element

### ISSUE THREAD

**Issue by Ahmad-Magdy** [go-bongo/bongo#22]
Hi 
now in bongo there is 3 operations insert , delete and find 
what if i need to modify exciting element what i should do

**Comment by securingsincity** [comment]
@Ahmad-Magdy Bongo supports updates as well. If you save a document and it has an `Id` defined it will do an update and not an insert.

**Comment by LennyPenny** [comment]
There might be cases where I would only want to do an update but not an insert if the document id doesn't exist. 
If the documentid doesn't exist I would want to have an error returned. 

Is there a way to do this with bongo without using the raw mgo sessiob?
