### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by gugadev** [go-bongo/bongo#31]
Just asking. Last commit was on October. Do you have a feature roadmap or the main focus is stability, like mgo?

Best regards and congratz for your awesome work.

**Comment by securingsincity** [comment]
@gugadev there is no roadmap. I haven't actively worked on bongo in a few years. I know people use it in production so if there were a critical issue I would help patch it. However, I don't see much activity happening in the future.

**Comment by securingsincity** [comment]
@gugadev with that said I would be open to pull requests for features

**Comment by gugadev** [comment]
Thank you for answer, @securingsincity. I hope send some PR in a near future. Regards.
